version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: ton-empire-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - default

  grafana:
    image: grafana/grafana:10.2.0
    container_name: ton-empire-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - default

  node-exporter:
    image: prom/node-exporter:v1.7.0
    container_name: ton-empire-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - default

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: ton-empire-postgres-exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/ton_empire?sslmode=disable"
    depends_on:
      - postgres
    networks:
      - default

  redis-exporter:
    image: oliver006/redis_exporter:v1.55.0
    container_name: ton-empire-redis-exporter
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: "redis:6379"
    depends_on:
      - redis
    networks:
      - default

volumes:
  prometheus_data:
  grafana_data:

networks:
  default:
    external:
      name: backend_default